source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ChipmunkSwiftWrapper_Example', :exclusive => true do
  pod "ChipmunkSwiftWrapper", :path => "../"
end

target 'ChipmunkSwiftWrapper_Tests', :exclusive => true do
  pod "ChipmunkSwiftWrapper", :path => "../"

  
end
